[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd server && npm ci']

[phases.build]
cmds = ['echo "No build step needed for server"']

[start]
cmd = 'cd server && npm start'